export const AUTH_START='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_FAIL='AUTH_FAIL';
export const AUTH_LOGOUT='AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH='SET_AUTH_REDIRECT_PATH';
export const SUBTRACT_LIFE='SUBTRACT_LIFE';


export const UPDATE_TIME='UPDATE_TIME';
export const SUBTRACT_TIME='SUBTRACT_TIME';